In [1]:
import urllib.parse,urllib.request,urllib.error
import pandas as pd

#!conda install -c conda-fo beautifulsoup4
from bs4 import BeautifulSoup

# The down two lines of code are regarding opening of url and downloading the data
url  = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
html = urllib.request.urlopen(url)

# This line is cleaning the HTML code with BeautifulSoup
soup = BeautifulSoup(html,'html.parser')

# Then inserting the table data of the wikipedia page 
table = soup.find_all('table')[0] 

# Now loading the Data to list using pandas read_html
lst = pd.read_html(str(table))

# Converting List to pandas data frame 
df = pd.DataFrame(lst[0])

In [2]:
# Removing the Not assigned Borough from data frame
df = df[df["Borough"] != "Not assigned"]

In [3]:
df.shape
df.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor

In [4]:
from geopy.geocoders import Nominatim # import geocoder

latitude = []
longitude = []

address_register = list(df["Neighbourhood"] + ' ' + df["Borough"] )

geocoder = Nominatim() 

for address in address_register:
    try:
        location = geocoder.geocode(address)
        latitude.append(location.latitude)
        longitude.append(location.longitude)

    except:
        latitude.append(0.0)
        longitude.append(0.0)

C:\Users\ganeshsubramanyam\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Using Nominatim with the default "geopy/1.20.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

In [5]:
df["Latitude"]  = pd.DataFrame(latitude)
df["Longitude"] = pd.DataFrame(longitude)
print(df.shape)

(210, 5)

    Postcode           Borough             Neighbourhood   Latitude  Longitude
2        M3A        North York                 Parkwoods   0.000000   0.000000
3        M4A        North York          Victoria Village  43.722778 -79.450933
4        M5A  Downtown Toronto              Harbourfront  43.722079 -79.437507
5        M6A        North York          Lawrence Heights   0.000000   0.000000
6        M6A        North York            Lawrence Manor  53.740434  -2.460322
..       ...               ...                       ...        ...        ...
281      M8Z         Etobicoke  Kingsway Park South West        NaN        NaN
282      M8Z         Etobicoke                 Mimico NW        NaN        NaN
283      M8Z         Etobicoke        The Queensway West        NaN        NaN
284      M8Z         Etobicoke     Royal York South West        NaN        NaN
285      M8Z         Etobicoke            South of Bloor        NaN        NaN

[210 rows x 5 columns]

In [9]:
df.head()

  Postcode           Borough     Neighbourhood   Latitude  Longitude
2      M3A        North York         Parkwoods   0.000000   0.000000
3      M4A        North York  Victoria Village  43.722778 -79.450933
4      M5A  Downtown Toronto      Harbourfront  43.722079 -79.437507
5      M6A        North York  Lawrence Heights   0.000000   0.000000
6      M6A        North York    Lawrence Manor  53.740434  -2.460322